import { Bricolage_Grotesque, Pacifico } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/navbar/Navbar";
import Footer from "@/shared/footer/Footer";

const pacifico = Pacifico({
  weight: "400",
  variable: "--font-pacifico",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bricolageGrotesque.variable} ${pacifico.variable} antialiased font-bricolageGrotesque`}
      >
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
